a = input('Digite algo: ')
print('O tipo primitivo desse valor é', type(a))
print("Só tem espacos? ", a.isspace())
print('è um numero? ', a.isnumeric())
print('E alfabetico? ', a.isalpha())
print('E alfanumerico? ', a.isalnum())
print('Esta em maiuscula? ', a.isupper())
print('Esta em minuscula? ', a.islower())
print('Esta capitalizada? ', a.istitle())